version: '3.7'

services:
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_data:/usr/src/app

  backend:
    depends_on:
      - redis
    build: ./backend
    command: python manage.py run -h 0.0.0.0
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend:/usr/src/app

  frontend:
    depends_on:
      - backend
    build: ./frontend
    command: ng serve --host 0.0.0.0 --poll 1
    restart: always
    ports:
      - 4200:4200
    volumes:
    - ./frontend:/usr/src/app
volumes:
  redis_data: