services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #    image: docker.nghiemphan.de/admin/takeawaybill-backend:latest
    #    command: python manage.py run -h 0.0.0.0 --port=5005
    #    command: gunicorn backend.project:app
    #    entrypoint: gunicorn backend.project:app
    restart: always
    ports:
      - 5005:5005
    env_file:
      - ./.env.dev
#    volumes:
#      - ./backend:/usr/src/app

#  frontend:
#    depends_on:
#      - backend
#    build: ./frontend
#    command: ng serve --host 0.0.0.0 --poll 1 --port 4205
#    restart: always
#    ports:
#      - 4205:4205
#    volumes:
#    - ./frontend:/usr/src
